# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-04 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20190504_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
